<Project>
    <PropertyGroup>
        <Version>0.1.0</Version>

        <Authors>TheVekT</Authors>
        <Company>MineLauncher</Company>
        <Copyright>Copyright © 2026</Copyright>
        
        <OutputPath>$(SolutionDir)Build\$(Configuration)\</OutputPath>

        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>
</Project>