<Project>
    <PropertyGroup>
        <Version Condition="'$(Version)' == ''">0.0.2-beta</Version>
        
        <_NumericVersion>$(Version.Split('-')[0])</_NumericVersion>
        <_NumericVersion>$(_NumericVersion.Split('+')[0])</_NumericVersion>
        
        <AssemblyVersion Condition="'$(AssemblyVersion)' == ''">$(_NumericVersion)</AssemblyVersion>
        <FileVersion Condition="'$(FileVersion)' == ''">$(_NumericVersion)</FileVersion>
        
        <InformationalVersion Condition="'$(InformationalVersion)' == ''">$(Version)</InformationalVersion>

        <Authors>TheVekT</Authors>
        <Company>Cuda Launcher</Company>
        <Copyright>Copyright © 2026</Copyright>

        <OutputPath>$(SolutionDir)Build\$(Configuration)\</OutputPath>
        <PublishDir>$(SolutionDir)Build\$(Configuration)\</PublishDir>

        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>

        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    </PropertyGroup>
</Project>