<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <AssemblyName>Mine Launcher</AssemblyName>
  </PropertyGroup>
  <PropertyGroup>
    <SelfContained>true</SelfContained>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\Icons\fabric-default.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Icons\forge-default.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Icons\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Icons\neoforge-default.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Images\banner-default.jpg" />
    <Content Include="Assets\Icons\optifine-default.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Images\banner-default.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Skins\sk1.png" />
    <Resource Include="Assets\Skins\sk1.png" />
    <None Remove="Assets\Skins\sk2.png" />
    <Resource Include="Assets\Skins\sk2.png" />
    <None Remove="Assets\Skins\sk4.png" />
    <Resource Include="Assets\Skins\sk4.png" />
    <None Remove="Assets\Skins\sk3.png" />
    <Resource Include="Assets\Skins\sk3.png" />
    <None Remove="Assets\Skins\TheVekT(NOW).png" />
    <Resource Include="Assets\Skins\TheVekT(NOW).png" />
    <!-- Ensure theme XAML files are compiled as Page so CLR types in XAML resolve correctly -->
    <None Remove="Assets\Icons\150px-Yellow_Glazed_Terracotta_(S)_JE1_BE1.png" />
    <Content Include="Assets\Icons\150px-Yellow_Glazed_Terracotta_(S)_JE1_BE1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-TNT_JE3_BE2.png" />
    <Content Include="Assets\Icons\150px-TNT_JE3_BE2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Stone_JE8.png" />
    <Content Include="Assets\Icons\150px-Stone_JE8.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Smithing_Table_JE2_BE2.png" />
    <Content Include="Assets\Icons\150px-Smithing_Table_JE2_BE2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Sand_JE5_BE3.png" />
    <Content Include="Assets\Icons\150px-Sand_JE5_BE3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Red_Glazed_Terracotta_(S)_JE1_BE1.png" />
    <Content Include="Assets\Icons\150px-Red_Glazed_Terracotta_(S)_JE1_BE1.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Orange_Glazed_Terracotta_(S)_JE2_BE2.png" />
    <Content Include="Assets\Icons\150px-Orange_Glazed_Terracotta_(S)_JE2_BE2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Oak_Log_(UD)_JE8_BE3.png" />
    <Content Include="Assets\Icons\150px-Oak_Log_(UD)_JE8_BE3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Netherrack_JE4_BE2.png" />
    <Content Include="Assets\Icons\150px-Netherrack_JE4_BE2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Glass_JE4_BE2.png" />
    <Content Include="Assets\Icons\150px-Glass_JE4_BE2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Glowstone_BE.png" />
    <Content Include="Assets\Icons\150px-Glowstone_BE.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Cobblestone_JE5_BE3.png" />
    <Content Include="Assets\Icons\150px-Cobblestone_JE5_BE3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Chest.gif" />
    <Content Include="Assets\Icons\150px-Chest.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Bookshelf_JE4_BE2.png" />
    <Content Include="Assets\Icons\150px-Bookshelf_JE4_BE2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Block_of_Diamond_JE5_BE3.png" />
    <Content Include="Assets\Icons\150px-Block_of_Diamond_JE5_BE3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Bedrock_JE2_BE2.png" />
    <Content Include="Assets\Icons\150px-Bedrock_JE2_BE2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Anvil_(N)_BE3.png" />
    <Content Include="Assets\Icons\150px-Anvil_(N)_BE3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\120px-Poison_JE3_BE2.png" />
    <Content Include="Assets\Icons\120px-Poison_JE3_BE2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\120px-Impulse_Command_Block_JE5_BE2.png" />
    <Content Include="Assets\Icons\120px-Impulse_Command_Block_JE5_BE2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\120px-Furnace_(S)_JE4.png" />
    <Content Include="Assets\Icons\120px-Furnace_(S)_JE4.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\120px-Enchanting_Table_JE4_BE2.png" />
    <Content Include="Assets\Icons\120px-Enchanting_Table_JE4_BE2.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\120px-Emerald_JE3_BE3.png" />
    <Content Include="Assets\Icons\120px-Emerald_JE3_BE3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\120px-Crafting_Table_JE4_BE3.png" />
    <Content Include="Assets\Icons\120px-Crafting_Table_JE4_BE3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\120px-Bricks_JE5_BE3.png" />
    <Content Include="Assets\Icons\120px-Bricks_JE5_BE3.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\116px-Lectern_with_Book_(S).png" />
    <Content Include="Assets\Icons\116px-Lectern_with_Book_(S).png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\quilt-default.png" />
    <Content Include="Assets\Icons\quilt-default.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Icons\150px-Grass_Block_JE7_BE6.png" />
    <Content Include="Assets\Icons\150px-Grass_Block_JE7_BE6.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Languages\uk-UA.json" />
    <Content Include="Assets\Languages\uk-UA.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Page Remove="Assets\Themes\CyberPunk.xaml" />
    <Page Remove="Assets\Themes\default-dark.xaml" />
    <Page Remove="Assets\Themes\default-light.xaml" />
    <Page Remove="Assets\Themes\SteamPunk.xaml" />
    <None Remove="Assets\Themes\CyberPunk.zip" />
    <Content Include="Assets\Themes\CyberPunk.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Themes\SteamPunk.zip" />
    <Content Include="Assets\Themes\SteamPunk.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Resources\Pages\Installations.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Resources\Pages\Play.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Resources\Pages\Skins.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Resources\Styles\Global.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Resources\Controls\CustomTitleBar.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Assets\Themes\Theme.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Assets\Themes\Default-Light\Theme.xaml">
      <Generator>MSBuild:Compile</Generator>
      <XamlRuntime>Wpf</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <!-- Ensure other theme files are compiled as Page -->
  </ItemGroup>

  <ItemGroup>
    <Content Update="Assets\Images\banner-default.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Languages\en.json" />
    <Content Include="Assets\Languages\en-US.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <None Remove="Assets\Languages\ru.json" />
    <None Remove="Assets\Themes\Fonts\Rajdhani-Medium.ttf" />
    <!-- theme files must not be Content when they define CLR types; compiled as Page above -->
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\Skins\" />
    <Folder Include="Assets\Themes\" />
    <Folder Include="Resources\Embedded\Themes\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Launcher.Core\Launcher.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\Embedded\default-light.zip" />
    <None Remove="Resources\Embedded\default-dark.zip" />
    <None Remove="Resources\Embedded\Themes\default-dark.zip" />
    <EmbeddedResource Include="Resources\Embedded\Themes\default-dark.zip" />
    <None Remove="Resources\Embedded\Themes\default-light.zip" />
    <EmbeddedResource Include="Resources\Embedded\Themes\default-light.zip" />
  </ItemGroup>

</Project>
