<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup>
        <OutputPath Condition="'$(Configuration)' == 'Debug'">..\Build\Debug\</OutputPath>
        <OutputPath Condition="'$(Configuration)' == 'Release'">..\Build\Release\</OutputPath>

        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="CmlLib.Core" Version="4.0.6" />
      <PackageReference Include="CmlLib.Core.Auth.Microsoft" Version="3.3.0" />
      <PackageReference Include="CmlLib.Core.Installer.Forge" Version="1.1.0" />
      <PackageReference Include="CmlLib.Core.Installer.NeoForge" Version="4.0.0" />
    </ItemGroup>

</Project>
