<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <AssemblyName>Launcher Updater</AssemblyName>
        <ApplicationIcon>..\Launcher.UI.WPF\icon.ico</ApplicationIcon>
    </PropertyGroup>
    <PropertyGroup>
        <SelfContained>true</SelfContained>
    </PropertyGroup>
    <ItemGroup>
      <None Include="..\Launcher.UI.WPF\icon.ico">
        <Link>icon.ico</Link>
      </None>
    </ItemGroup>
</Project>
